version: '3.6'

services:

  php:
    image: twenty7/music-showcase-app:latest
    build: ./
    restart: always
    volumes:
      - ./docker/logs:/var/log
    networks:
      - showcase

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    command: ["/bin/bash", "-c", "sed 's/NGINX_HOST/${NGINX_HOST}/g' /etc/nginx/conf.d/site.conf.tmp > /etc/nginx/conf.d/site.conf && nginx -g 'daemon off;'"]
    volumes:
      - ./:/var/www/showcase:cached
      - ./docker/nginx.conf:/etc/nginx/conf.d/site.conf.tmp
      - ./docker/logs:/var/log/nginx
    networks:
      - showcase
    depends_on:
      - php
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "musicbrainz"
      POSTGRES_PASSWORD: "musicbrainz"
    volumes:
      - ./docker/db-data:/var/lib/postgresql/data/
    networks:
      - showcase

networks:
  showcase:
    driver: bridge
