version: '3.6'

services:

  php:
    build: ./php-fpm
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ../:/code:cached
      - ./logs:/var/log
    networks:
      - showcase

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8080:80"
    environment:
    # - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    volumes:
      - ../:/code:cached
      - ./nginx.conf:/etc/nginx/conf.d/site.conf
      - ./logs:/var/log/nginx
    networks:
      - showcase
    depends_on:
      - php
      - postgres

  postgres:
    image: postgres
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: "musicbrainz"
      POSTGRES_PASSWORD: "musicbrainz"
    volumes:
      - ./db-data:/var/lib/postgresql/data/
    networks:
      - showcase

networks:
  showcase:
    driver: bridge
